# see https://github.com/probe-rs/probe-rs/blob/v0.30.0/probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/config/default.toml.

[default.probe]
protocol = "Jtag"

[default.rtt]
enabled = true
up_channels = [
    # TODO why show_timestamps = true does not actually display any timestamp?
    { channel = 0, mode = "BlockIfFull", format = "Defmt", show_timestamps = true, show_location = true },
]
